- name: Setup MinIO distributed on lab nodes
  hosts: nodes
  become: true
  tasks:
    - name: Create MinIO data directories
      file:
        path: "/mnt/data{{ item }}"
        state: directory
        owner: "{{ ansible_user }}"
        mode: '0755'
      loop: "{{ range(1,5) | list }}"

    - name: Download MinIO binary
      get_url:
        url: "https://dl.min.io/server/minio/release/linux-amd64/minio"
        dest: "/usr/local/bin/minio"
        mode: '0755'

    - name: Open firewall ports for MinIO
      firewalld:
        port: "{{ item }}/tcp"
        permanent: true
        state: enabled
      loop:
        - 9000
        - 9001

    - name: Reload firewall
      command: firewall-cmd --reload
