- name: Mount /dev/sdb to /mnt/data and persist in fstab
  hosts: nodes
  become: true
  tasks:

    - name: Create mount point
      file:
        path: /mnt/data
        state: directory
        mode: '0755'

    - name: Format /dev/sdb as ext4 (if not already)
      filesystem:
        fstype: ext4
        dev: /dev/sdb
      ignore_errors: true  # skip error if already formatted

    - name: Add /dev/sdb to /etc/fstab
      mount:
        path: /mnt/data
        src: /dev/sdb
        fstype: ext4
        opts: defaults
        state: mounted
